### ISSUE TITLE
Random typo in world2.py

### ISSUE THREAD

**Issue by afvincent** [cvanwynsberghe/pyworld2#1]
It should be [numerica*l*](https://github.com/cvanwynsberghe/pyworld2/blob/77c8af66ceac5f1030bad246979013714585db50/pyworld2/world2.py#L209), should it not?

**Comment by cvanwynsberghe** [comment]
Typo is corrected in the [last commit](https://github.com/cvanwynsberghe/pyworld2/commit/99c72dcc0216a0dcc5c0d71fc77b0108b609ef2d) .
